useNodeVersion: 24.13.1

packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "25.2.3"
  "@vitest/coverage-v8": "4.0.18"
  "@vitest/ui": "4.0.18"
  oxfmt: "0.32.0"
  oxlint: "1.47.0"
  typescript: "5.9.3"
  vitest: "4.0.18"

allowBuilds:
  esbuild: false
  workerd: false
  sharp: false

minimumReleaseAge: 1440

trustPolicy: no-downgrade
