name = "kimulaco-discord-bot-dev"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[triggers]
crons = ["0 1 * * 1"] # 毎週月曜日 日本時間10時に実行

[env.production]
name = "kimulaco-discord-bot"
workers_dev = false

[env.development]
name = "kimulaco-discord-bot-dev"
